// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
      apiKey: 'AIzaSyCTPr1Z81L_rqSRDLK0AdL7t8E_HhUySd4',
      appId: '1:786326787465:web:e34a1f8077099c1c997d58',
      messagingSenderId: '786326787465',
      projectId: 'gmsg-de9a0',
      authDomain: 'gmsg-de9a0.firebaseapp.com',
      storageBucket: 'gmsg-de9a0.appspot.com',
      measurementId: 'G-13L81DCV8F',
      databaseURL: 'https://gmsg-de9a0-default-rtdb.firebaseio.com/');

  static const FirebaseOptions android = FirebaseOptions(
      apiKey: 'AIzaSyDa-RaZUtY2_YLHsBTx5FYgpt4I-CGwp6c',
      appId: '1:786326787465:android:d91e994b7e639780997d58',
      messagingSenderId: '786326787465',
      projectId: 'gmsg-de9a0',
      storageBucket: 'gmsg-de9a0.appspot.com',
      databaseURL: 'https://gmsg-de9a0-default-rtdb.firebaseio.com/');

  static const FirebaseOptions ios = FirebaseOptions(
      apiKey: 'AIzaSyBZyZbdSGCnNTBswFQJTrDbeJ3jJJBNt5Y',
      appId: '1:786326787465:ios:1d748e954f29932a997d58',
      messagingSenderId: '786326787465',
      projectId: 'gmsg-de9a0',
      storageBucket: 'gmsg-de9a0.appspot.com',
      iosClientId:
          '786326787465-njhgvnoqu7uo44kkjp96dpkqrlj6qig0.apps.googleusercontent.com',
      iosBundleId: 'com.example.gsmg',
      databaseURL: 'https://gmsg-de9a0-default-rtdb.firebaseio.com/');
}
